### ISSUE TITLE
文本侧的onnx模型转换为int8的engine模型

### ISSUE THREAD

**Issue by epidemiiic** [L-fountain/clip2onnx#1]
作者你好！我想问一下文本侧的onnx模型想转换为int8的engine模型，该如何处理数据并且引入训练集calibration_stream？

**Comment by L-fountain** [comment]
数据预处理你指的是token那些步骤吗，python 的话代码跟之前一样，c++的代码可以看我另一个项目分支里写的实现。如果你要做int8量化校准的话，我理解的是跟图像的操作一样，只不过预处理过程不同。

**Comment by L-fountain** [comment]
> 作者你好！我想问一下文本侧的onnx模型想转换为int8的engine模型，该如何处理数据并且引入训练集calibration_stream？

数据预处理你指的是token那些步骤吗，python 的话代码跟之前一样，c++的代码可以看我另一个项目分支里写的实现。如果你要做int8量化校准的话，我理解的是跟图像的操作一样，只不过预处理过程不同。

**Comment by epidemiiic** [comment]
谢谢回复！我指的就是python代码对文本的预处理，我想知道preprocess里面的数组mean和stddev是怎么得到的

**Comment by epidemiiic** [comment]
我想知道preprocess里面的数组mean和stddev是怎么得到的

**Comment by L-fountain** [comment]
> 谢谢回复！我指的就是python代码对文本的预处理，我想知道preprocess里面的数组mean和stddev是怎么得到的





> 谢谢回复！我指的就是python代码对文本的预处理，我想知道preprocess里面的数组mean和stddev是怎么得到的

emmmm,我感觉对文本来说减均值除以方差应该是不用的。因为tokenize将文本编码成词向量以后，这个词向量在encoder_text开始的部分是一个线性映射的关系，你如果对文本做了减均值除以方差，结果就对不上了。preprocess里面的数组mean和stddev是原始clip模型的预处理步骤直接拿来的，这个是Imagenet数据集的均值和方差。

**Comment by L-fountain** [comment]
> 谢谢回复！我指的就是python代码对文本的预处理，我想知道preprocess里面的数组mean和stddev是怎么得到的

emmmm,我感觉对文本来说减均值除以方差应该是不用的。因为tokenize将文本编码成词向量以后，这个词向量在encoder_text开始的部分是一个线性映射的关系，你如果对文本做了减均值除以方差，结果就对不上了。preprocess里面的数组mean和stddev是原始clip模型的预处理步骤直接拿来的，这个是Imagenet数据集的均值和方差。

**Comment by L-fountain** [comment]
> 谢谢回复！我指的就是python代码对文本的预处理，我想知道preprocess里面的数组mean和stddev是怎么得到的

emmmm,我感觉对文本来说减均值除以方差应该是不用的。因为tokenize将文本编码成词向量以后，这个词向量在encoder_text开始的部分是一个整数序列转化为密集向量的关系，你如果对文本做了减均值除以方差，就没法进行nn.Embedding(vocab_size,trannsformer_width)了。preprocess里面的数组mean和stddev是原始clip模型的预处理步骤直接拿来的，这个是Imagenet数据集的均值和方差。

**Comment by epidemiiic** [comment]
> > 谢谢回复！我指的就是python代码对文本的预处理，我想知道preprocess里面的数组mean和stddev是怎么得到的
> 
> emmmm,我感觉对文本来说减均值除以方差应该是不用的。因为tokenize将文本编码成词向量以后，这个词向量在encoder_text开始的部分是一个整数序列转化为密集向量的关系，你如果对文本做了减均值除以方差，就没法进行nn.Embedding(vocab_size,trannsformer_width)了。preprocess里面的数组mean和stddev是原始clip模型的预处理步骤直接拿来的，这个是Imagenet数据集的均值和方差。

谢谢！那文本侧的int8量化还需要calibration_data数据集进行校正吗？应该怎么处理文本数据，还能否使用clip的tokenize函数？

**Comment by L-fountain** [comment]
> > > 谢谢回复！我指的就是python代码对文本的预处理，我想知道preprocess里面的数组mean和stddev是怎么得到的
> > 
> > 
> > emmmm,我感觉对文本来说减均值除以方差应该是不用的。因为tokenize将文本编码成词向量以后，这个词向量在encoder_text开始的部分是一个整数序列转化为密集向量的关系，你如果对文本做了减均值除以方差，就没法进行nn.Embedding(vocab_size,trannsformer_width)了。preprocess里面的数组mean和stddev是原始clip模型的预处理步骤直接拿来的，这个是Imagenet数据集的均值和方差。
> 
> 谢谢！那文本的int8量化还需要calibration_data 数据集进行校正吗？应该怎么处理文本数据，还能否使用clip的tokenize函数？

clip的tenkenize函数对最终结果是不会有影响的，所以还是可以当预处理使用。calibration_data数据集对tranformer网络校准还是需要的。

**Comment by epidemiiic** [comment]
明白了，谢谢！

**Comment by epidemiiic** [comment]
作者您好，我按照我的需求更改了文本侧int8量化的方法，但是报错如下：

> `[/transformer/resblocks/resblocks.0/ln_1/Cast_output_0 -> (77, -1, 512)[FLOAT]], [transformer.resblocks.0.ln_1.weight -> (512)[FLOAT]], [transformer.resblocks.0.ln_1.bias -> (512)[FLOAT]],
[05/19/2024-21:47:41] [TRT] [I] No importer registered for op: LayerNormalization. Attempting to import as plugin.
[05/19/2024-21:47:41] [TRT] [I] Searching for plugin: LayerNormalization, plugin_version: 1, plugin_namespace:
Completed parsing of ONNX file
Building an engine from file ../my_train/t.onnx; this may take a while...
Int8 mode enabled
[05/19/2024-21:47:41] [TRT] [E] 4: [network.cpp::nvinfer1::Network::validate::2770] Error Code 4: Internal Error (Network must have at least one output)
Failed to create the engine
None
Traceback (most recent call last):
  File "tensorrt_clip_int8_txt.py", line 76, in <module>
    main()
  File "tensorrt_clip_int8_txt.py", line 71, in main
    assert engine_fixed, 'Brokenls engine_fixed'
AssertionError: Brokenls engine_fixed`

下面是我的代码，如果您有时间，可以帮我看看问题出在哪里吗？
`import numpy as np
import clip
# import torch
# import torch.nn as nn
import util_trt
import glob, os, cv2
import torch


BATCH_SIZE = 4
BATCH = 25
TEXT_LENGTH = 77

onnx_model_path = '../my_train/t.onnx'
CALIB_TXT_DIR = '../example/cifar100.txt'
device = "cuda" if torch.cuda.is_available() else "cpu"


def preprocess(word):
    text_string = f"a photo of a {word}"
    text = clip.tokenize([text_string]).to(device)
    text = text.cpu().numpy()
    text = text[0]
    return text

class DataLoader:
    def __init__(self):
        self.index = 0
        self.length = BATCH
        self.batch_size = BATCH_SIZE
        self.txt_list = [i.strip() for i in open(CALIB_TXT_DIR).readlines()]
        assert len(self.txt_list) > self.batch_size * self.length, '{} must contains more than '.format(
            CALIB_TXT_DIR) + str(self.batch_size * self.length) + ' words to calib'
        print('found all {} words to calib.'.format(len(self.txt_list)))
        self.calibration_data = np.zeros((self.batch_size, TEXT_LENGTH), dtype=np.int32)

    def reset(self):
        self.index = 0

    def next_batch(self):
        if self.index < self.length:
            for i in range(self.batch_size):
                assert os.path.exists(self.txt_list[i + self.index * self.batch_size]), 'not found!!'
                word = self.txt_list[i + self.index * self.batch_size]
                text = preprocess(word)
                self.calibration_data[i] = text

            self.index += 1

            # example only
            return np.ascontiguousarray(self.calibration_data, dtype=np.int32)
        else:
            return np.array([])

    def __len__(self):
        return self.length


def main():
    # onnx2trt
    fp16_mode = False
    int8_mode = True
    print('*** onnx to tensorrt begin ***')
    calibration_stream = DataLoader()
    engine_model_path = "TmodelInt8.engine"
    calibration_table = 'best_calibration_txt.cache'
    engine_fixed = util_trt.get_engine(BATCH_SIZE, onnx_model_path, engine_model_path, fp16_mode=fp16_mode,
                                       int8_mode=int8_mode, calibration_stream=calibration_stream,
                                       calibration_table_path=calibration_table, save_engine=True)
    print(engine_fixed)
    assert engine_fixed, 'Brokenls engine_fixed'
    print('*** onnx to tensorrt completed ***\n')


if __name__ == '__main__':
    main()`

**Comment by epidemiiic** [comment]
作者您好，我按照我的需求更改了文本侧int8量化的方法，但是报错如下：
`Building an engine from file ../my_train/t.onnx; this may take a while...
Int8 mode enabled
[05/19/2024-21:47:41] [TRT] [E] 4: [network.cpp::nvinfer1::Network::validate::2770] Error Code 4: Internal Error (Network must have at least one output)
Failed to create the engine
None
Traceback (most recent call last):
  File "tensorrt_clip_int8_txt.py", line 76, in <module>
    main()
  File "tensorrt_clip_int8_txt.py", line 71, in main
    assert engine_fixed, 'Brokenls engine_fixed'
AssertionError: Brokenls engine_fixed`

下面是我的代码，如果您有时间，可以帮我看看问题出在哪里吗？
`import numpy as np
import clip
# import torch
# import torch.nn as nn
import util_trt
import glob, os, cv2
import torch


BATCH_SIZE = 4
BATCH = 25
TEXT_LENGTH = 77

onnx_model_path = '../my_train/t.onnx'
CALIB_TXT_DIR = '../example/cifar100.txt'
device = "cuda" if torch.cuda.is_available() else "cpu"


def preprocess(word):
    text_string = f"a photo of a {word}"
    text = clip.tokenize([text_string]).to(device)
    text = text.cpu().numpy()
    text = text[0]
    return text

class DataLoader:
    def __init__(self):
        self.index = 0
        self.length = BATCH
        self.batch_size = BATCH_SIZE
        self.txt_list = [i.strip() for i in open(CALIB_TXT_DIR).readlines()]
        assert len(self.txt_list) > self.batch_size * self.length, '{} must contains more than '.format(
            CALIB_TXT_DIR) + str(self.batch_size * self.length) + ' words to calib'
        print('found all {} words to calib.'.format(len(self.txt_list)))
        self.calibration_data = np.zeros((self.batch_size, TEXT_LENGTH), dtype=np.int32)

    def reset(self):
        self.index = 0

    def next_batch(self):
        if self.index < self.length:
            for i in range(self.batch_size):
                assert os.path.exists(self.txt_list[i + self.index * self.batch_size]), 'not found!!'
                word = self.txt_list[i + self.index * self.batch_size]
                text = preprocess(word)
                self.calibration_data[i] = text

            self.index += 1

            # example only
            return np.ascontiguousarray(self.calibration_data, dtype=np.int32)
        else:
            return np.array([])

    def __len__(self):
        return self.length


def main():
    # onnx2trt
    fp16_mode = False
    int8_mode = True
    print('*** onnx to tensorrt begin ***')
    calibration_stream = DataLoader()
    engine_model_path = "TmodelInt8.engine"
    calibration_table = 'best_calibration_txt.cache'
    engine_fixed = util_trt.get_engine(BATCH_SIZE, onnx_model_path, engine_model_path, fp16_mode=fp16_mode,
                                       int8_mode=int8_mode, calibration_stream=calibration_stream,
                                       calibration_table_path=calibration_table, save_engine=True)
    print(engine_fixed)
    assert engine_fixed, 'Brokenls engine_fixed'
    print('*** onnx to tensorrt completed ***\n')


if __name__ == '__main__':
    main()`

**Comment by epidemiiic** [comment]
作者您好，我按照我的需求更改了文本侧int8量化的方法，但是产生了报错信息。下面是我的代码和报错，如果您有时间，可以帮我看看问题出在哪里吗？
### 报错

> Completed parsing of ONNX file
> Building an engine from file ../my_train/t.onnx; this may take a while...
> Int8 mode enabled
> [05/19/2024-21:47:41] [TRT] [E] 4: [network.cpp::nvinfer1::Network::validate::2770] Error Code 4: Internal Error (Network must have at least one output)
> Failed to create the engine
> None
> Traceback (most recent call last):
>   File "tensorrt_clip_int8_txt.py", line 76, in <module>
>     main()
>   File "tensorrt_clip_int8_txt.py", line 71, in main
>     assert engine_fixed, 'Brokenls engine_fixed'
> AssertionError: Brokenls engine_fixed

### 代码
```
import numpy as np
import clip
import util_trt
import glob, os, cv2
import torch


BATCH_SIZE = 4
BATCH = 25
TEXT_LENGTH = 77

onnx_model_path = '../my_train/t.onnx'
CALIB_TXT_DIR = '../example/cifar100.txt'
device = "cuda" if torch.cuda.is_available() else "cpu"


def preprocess(word):
    text_string = f"a photo of a {word}"
    text = clip.tokenize([text_string]).to(device)
    text = text.cpu().numpy()
    text = text[0]
    return text

class DataLoader:
    def __init__(self):
        self.index = 0
        self.length = BATCH
        self.batch_size = BATCH_SIZE
        self.txt_list = [i.strip() for i in open(CALIB_TXT_DIR).readlines()]
        print('found all {} words to calib.'.format(len(self.txt_list)))
        self.calibration_data = np.zeros((self.batch_size, TEXT_LENGTH), dtype=np.int32)

    def reset(self):
        self.index = 0

    def next_batch(self):
        if self.index < self.length:
            for i in range(self.batch_size):
                word = self.txt_list[i + self.index * self.batch_size]
                text = preprocess(word)
                self.calibration_data[i] = text

            self.index += 1

            # example only
            return np.ascontiguousarray(self.calibration_data, dtype=np.int32)
        else:
            return np.array([])

    def __len__(self):
        return self.length


def main():
    # onnx2trt
    fp16_mode = False
    int8_mode = True
    print('*** onnx to tensorrt begin ***')
    calibration_stream = DataLoader()
    engine_model_path = "TmodelInt8.engine"
    calibration_table = 'best_calibration_txt.cache'
    engine_fixed = util_trt.get_engine(BATCH_SIZE, onnx_model_path, engine_model_path, fp16_mode=fp16_mode,
                                       int8_mode=int8_mode, calibration_stream=calibration_stream,
                                       calibration_table_path=calibration_table, save_engine=True)
    print(engine_fixed)
    assert engine_fixed, 'Brokenls engine_fixed'
    print('*** onnx to tensorrt completed ***\n')


if __name__ == '__main__':
    main()`
```

**Comment by L-fountain** [comment]
我看报错怀疑是你的onnx模型导出有问题

**Comment by epidemiiic** [comment]
> 我看到报错怀疑是你的 onnx 模型导出有问题

我导出就是执行的”python -m model_conversion.to_onnx_textual -m "RN50" -o t.onnx“，只不过我用的是Rn50模型

还有一点就是，直接使用trtexec量化，图像侧onnx模型可以正常转换为engine模型；但文本侧不可以
命令行输入是：
`trtexec --onnx=t.onnx --saveEngine=TmodelInt8.engine --int8 `

**Comment by epidemiiic** [comment]
> 我看报错怀疑是你的onnx模型导出有问题

可以问一下您使用的tensorRT版本吗？

**Comment by L-fountain** [comment]
那还真是挺奇怪的，我自己用ViT版本的CLIP都是可以完成int8的。其实我这个代码也是从另一个人仓库拉的，理论上ViT和Resnet的版本对于文本没影响

**Comment by epidemiiic** [comment]
> 那还是挺奇怪的，我自己用ViT版本的CLIP都是可以完成int8的。其实我这个代码也是来自另一个人仓库拉的，理论上ViT和Resnet的版本对于文本没影响

感谢！那我可以再试试ViT看看会不会遇到同样的问题，那应该不是我的文本侧calibration_data写的有问题？

**Comment by L-fountain** [comment]
嗯，你再试试看

**Comment by epidemiiic** [comment]
> 嗯，你再试试看

你好，我在使用tensorrt_clip_int8.py这个代码转换vit-16的onnx模型为engine模型也遇到了问题，我想可能是版本问题，方便问下作者使用的tensorRT版本吗？
报错信息如下：
`Failed to create the engine
None
Traceback (most recent call last):
  File "tensorrt_clip_int8.py", line 77, in <module>
    main()
  File "tensorrt_clip_int8.py", line 72, in main
    assert engine_fixed, 'Brokenls engine_fixed'
AssertionError: Brokenls engine_fixed`

**Comment by L-fountain** [comment]
8.6.1.6



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月19日(周日) 晚上11:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [L-fountain/clip2onnx] 文本侧的onnx模型转换为int8的engine模型 (Issue #1)




  
嗯，你再试试看
  
你好，我在使用tensorrt_clip_int8.py这个代码转换vit-16的onnx模型为engine模型也遇到了问题，我想可能是版本问题，方便问下作者使用的tensorRT版本吗？
 报错信息如下：
 Failed to create the engine None Traceback (most recent call last): File "tensorrt_clip_int8.py", line 77, in <module&gt; main() File "tensorrt_clip_int8.py", line 72, in main assert engine_fixed, 'Brokenls engine_fixed' AssertionError: Brokenls engine_fixed

**Comment by epidemiiic** [comment]
> 8.6.1.6

感谢作者，今天换了个版本确实可以了
